title: Arumo-beta API Reference
description: 消耗品管理アプリArumo-betaのAPIリファレンス
author: Segnities007

# Jekyll theme - カスタムテーマを使用
theme: jekyll-theme-minimal

# カスタムCSSとJSの設定
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# カスタムCSSファイルの設定
sass:
  load_paths:
    - _sass
    - node_modules

# サイト設定
url: "https://segnities007.github.io"
baseurl: "/Arumobeta"

# ナビゲーション
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/segnities007/Arumobeta
  - title: Download App
    url: https://play.google.com/store/apps/details?id=com.segnities007.arumo_beta

# カスタムレイアウトの設定
layouts_dir: _layouts
includes_dir: _includes

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - API_REFERENCE.md 